// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./cq/providers"
  policy_directory = "./cq/policies"

  provider "k8s" {
    source  = "cloudquery/cq-provider-k8s"
    version = "latest"
  }
}

// All Provider Configurations
provider "k8s" {
  configuration {}
  resources = [
  "*"]
}

policy "k8s-policy-pack" {
  source = "./policy.hcl"
}
